import Navbar from "@/components/Navbar";
import "./globals.css";
import BacksoundToggle from "@/components/BacksoundToogle";
import CursorSparkle from "@/components/CursorSparkle"; 

export const metadata = {
  title: "BFC Alchemy 2 Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CursorSparkle />
        <Navbar />
        {children}
        <BacksoundToggle />
      </body>
    </html>
  );
}
